using UnityEngine;
using UnityEditor;
using UnityEditor.Animations;

/// <summary>
/// Generates a basic prefab for Uncle Nok, attaches an Animator component,
/// and assigns the Animator Controller created by UncleNokAnimatorSetup.
/// Run from the Unity menu:
/// CueStrike → Character System → Create Uncle Nok Prefab
/// </summary>
public static class UncleNokPrefabSetup
{
    private const string ControllerPath = "Assets/CueStrike/Characters/UncleNok/UncleNok.controller";
    private const string PrefabPath = "Assets/CueStrike/Characters/UncleNok/UncleNok_Prefab.prefab";

    [MenuItem("CueStrike/Character System/Create Uncle Nok Prefab")]
    public static void CreatePrefab()
    {
        // Load the animator controller – ensure it exists
        RuntimeAnimatorController controller = AssetDatabase.LoadAssetAtPath<RuntimeAnimatorController>(ControllerPath);
        if (controller == null)
        {
            Debug.LogError($"Animator controller not found at {ControllerPath}. Run \"Create Uncle Nok Animator\" first.");
            return;
        }

        // Ensure the target folder exists
        string folder = System.IO.Path.GetDirectoryName(PrefabPath);
        if (!AssetDatabase.IsValidFolder(folder))
        {
            AssetDatabase.CreateFolder("Assets/CueStrike/Characters", "UncleNok");
        }

        // Create a new GameObject to serve as the mascot placeholder
        GameObject go = new GameObject("UncleNok");
        go.tag = "Untagged";

        // Add an Animator component and assign the controller
        Animator animator = go.AddComponent<Animator>();
        animator.runtimeAnimatorController = controller;

        // OPTIONAL: Add a simple visual representation (e.g., a capsule) so the mascot is visible in the scene
        GameObject visual = GameObject.CreatePrimitive(PrimitiveType.Capsule);
        visual.name = "Visual";
        visual.transform.SetParent(go.transform, false);
        visual.transform.localScale = new Vector3(0.5f, 1.8f, 0.5f);
        // Remove the collider generated by the primitive (not needed for mascot logic)
        Object.DestroyImmediate(visual.GetComponent<Collider>());

        // Save the GameObject as a prefab asset
        PrefabUtility.SaveAsPrefabAsset(go, PrefabPath);
        Debug.Log($"Uncle Nok prefab created at {PrefabPath}");

        // Clean up the temporary scene object
        Object.DestroyImmediate(go);
    }
}