$lines = @(
    "using System.Collections.Generic;",
    "using System.Linq;",
    "using System.Threading.Tasks;",
    "using UnityEditor;",
    "using UnityEngine;",
    "",
    "namespace CueStrike.Editor",
    "{",
    "    public static class MCPSelfTest",
    "    {",
    "        private const string MENU_PATH = \"Tools/CueStrike/MCP/Self-Test\";",
    "",
    "        [MenuItem(MENU_PATH, false, 100)]",
    "        public static void RunSelfTest()",
    "        {",
    "            var results = new List<string>();",
    "            bool allPassed = true;",
    "",
    "            results.Add(\"=== MCP Unity Tools Self-Test ===\");",
    "            results.Add(\"\");",
    "",
    "            bool serverRunning = CueStrike.MCP.McpServer.IsRunning;",
    "            results.Add(serverRunning ? \"PASS: MCP Server is running\" : \"FAIL: MCP Server is NOT running (open Tools CueStrike MCP Server and click Start)\");",
    "            if (!serverRunning) allPassed = false;",
    "",
    "            var tools = CueStrike.MCP.McpServer.GetTools();",
    "            int toolCount = tools.Count;",
    "            results.Add(toolCount > 0 ? \"PASS: {toolCount} MCP tools registered\" : \"FAIL: No MCP tools registered\");",
    "            if (toolCount == 0) allPassed = false;",
    "",
    "            foreach (var tool in tools)",
    "            {",
    "                results.Add($\"   {tool.Key}: {tool.Value.Description}\");",
    "            }",
    "",
    "            bool settingsExist = CheckMCPSettings();",
    "            results.Add(settingsExist ? \"PASS: MCP Settings asset found\" : \"WARN: MCP Settings asset not found\");",
    "",
    "            bool executeCodeWorks = TestExecuteCodeTool().Result;",
    "            results.Add(executeCodeWorks ? \"PASS: Execute Code tool works\" : \"FAIL: Execute Code tool failed\");",
    "            if (!executeCodeWorks) allPassed = false;",
    "",
    "            bool readFileWorks = TestReadFileTool().Result;",
    "            results.Add(readFileWorks ? \"PASS: Read File tool works\" : \"FAIL: Read File tool failed\");",
    "            if (!readFileWorks) allPassed = false;",
    "",
    "            bool listFilesWorks = TestListFilesTool().Result;",
    "            results.Add(listFilesWorks ? \"PASS: List Files tool works\" : \"FAIL: List Files tool failed\");",
    "            if (!listFilesWorks) allPassed = false;",
    "",
    "            bool searchFilesWorks = TestSearchFilesTool().Result;",
    "            results.Add(searchFilesWorks ? \"PASS: Search Files tool works\" : \"FAIL: Search Files tool failed\");",
    "            if (!searchFilesWorks) allPassed = false;",
    "",
    "            bool pinkCheck = CheckZeroPinkPolicy();",
    "            results.Add(pinkCheck ? \"PASS: Zero Pink Policy - No pink shaders detected\" : \"FAIL: Pink shaders found in scene/materials\");",
    "            if (!pinkCheck) allPassed = false;",
    "",
    "            bool audioCheck = CheckAudioLinks();",
    "            results.Add(audioCheck ? \"PASS: Audio links configured\" : \"WARN: Some audio clips missing\");",
    "",
    "            results.Add(\"\");",
    "            results.Add(allPassed ? \"=== ALL TESTS PASSED ===\" : \"=== SOME TESTS FAILED ===\");",
    "",
    "            foreach (var line in results)",
    "            {",
    "                if (line.StartsWith(\"PASS\")) Debug.Log(line);",
    "                else if (line.StartsWith(\"FAIL\")) Debug.LogError(line);",
    "                else if (line.StartsWith(\"WARN\")) Debug.LogWarning(line);",
    "                else Debug.Log(line);",
    "            }",
    "",
    "            string message = string.Join(\"\\n\", results);",
    "            EditorUtility.DisplayDialog(\"MCP Self-Test Results\", message, \"OK\");",
    "        }"
)
$lines | Set-Content 'c:\Users\mongo\UnityProjects\CueStrike\CueStrike_Project\Assets\CueStrike\Editor\MCPSelfTest.cs' -Encoding UTF8