name: Acquire Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Create Unity activation file
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: get_alf
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.4.4f1

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.4.4f1.alf
          path: ${{ steps.get_alf.outputs.filePath }}
